version: "3"
services:
   api-database:
      image: mongo:latest
      container_name: "api-database"
      hostname: mongo
      ports:
         - 27017:27017
   api:
      image: smsreesangamesh/greenhomefoods:0.0.2
      ports:
         - 8100:8100
      links:
         - api-database